language: lisp
sudo: required

env:
    matrix:
        - LISP=sbcl
        - LISP=ccl
        # These don't work because rutils tries to intern bordeaux-threads in the cl package
        # figure out how to fix this.
        #- LISP=ecl
        #- LISP=clisp

install:
    - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh

script:
    - cl -e '(ql:quickload :mexpr-tests)'
         -e '(unless (st:test :package :mexpr-tests)
               (uiop:quit 1))'
